title: Reflection Groups Network
description: An international research network on reflection groups, Coxeter groups, Weyl groups, complex reflection groups, root systems, hyperplane arrangements, braid groups, Artin groups
---
theme: minima

header_pages:
  - online-seminar/index.md
  - events/index.md
  - past-events/index.md
  - cool-ressources/index.md
  - about-rgn/index.md
